name:                flick-duration
synopsis:            work with durations of time using the Flick as the smallest unit
version:             1.0.0
github:              "pliosoft/flick-duration"
license:             BSD3
author:              "Christopher Lord"
maintainer:          "christopher@pliosoft.com"
copyright:           "(C) Christopher Lord (Pliosoft), All Rights Reserved"
category:            Time

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pliosoft/flick-duration#readme>

dependencies:
- base >= 4.7 && < 5
- clock >= 0.5 && < 1

library:
  source-dirs: src

tests:
  flick-duration-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flick-duration
    - hspec
    - QuickCheck
